### ISSUE TITLE
Documentation request: Example of docker image to run locust with playwright user plugin

### ISSUE THREAD

**Issue by teixeira-fernando** [SvenskaSpel/locust-plugins#120]
### Description:

I tried to create a Dockerfile with all the necessary dependencies to run a locust test with Playwright plugin. My idea was to scale multiple workers using docker-compose. Since I have not found something specific for the playwright-plugin in the documentation, I tried it by myself. However, I experienced a few issues which more people could also face in the process.

### Error description:

After adding all the necessary commands into the Dockerfile, I tried to build the image using `docker build .`. 
If we include the command `playwright install --with-deps`, we face the following permission error:

>  > [5/5] RUN playwright install --with-deps:                                                                                                                                                       
#8 1.501 Installing dependencies...                                                                                                                                                                
#8 1.517 Switching to root user to install dependencies...
#8 1.527 Password: su: Authentication failure
#8 2.532 Failed to install browsers
#8 2.532 Error: Installation process exited with code: 1

If I run instead just `playwright install` inside the container, it works. However, the browser installation path is not found during the test run with docker-compose. As we can see in the image below, it suggests us run actually  `playwright install --with-deps`.

![image](https://user-images.githubusercontent.com/32043860/234572816-178b2af1-8f6d-4961-9058-463a71326ef8.png)
 

### Last information:

I would like to help with the documentation about this part, but first, I need to find out how to properly make it work. Any ideas that could help me?

I will add below some Code Snippets to help to reproduce the issue. The test script can be anyone, including the script example already present here in the repository: [playwright-locust-example](https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/playwright_ex.py)

### Code Snippets:

**Dockerfile**

```
FROM locustio/locust:latest
RUN pip3 install python-dotenv
RUN pip3 install locust-plugins
RUN pip3 install playwright
RUN playwright install
```
**docker-compose.yml**

```
version: '3'
services:
  master:
    image: locust-master
    build: 
      context: .
      dockerfile: Dockerfile 
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    environment:
      - PYTHONUNBUFFERED=1
      - LOCUST_PLAYWRIGHT=1
    command: "-f /mnt/locust/locust-playwright-script.py --master --host=${HOST} --headless --html=report.html"
  
  worker:
    image: locust-worker
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/mnt/locust
    environment:
      - PYTHONUNBUFFERED=1
      - LOCUST_PLAYWRIGHT=1
    command: -f /mnt/locust/locust-playwright-script.py --worker --master-host master --host=${HOST}
```
