### ISSUE TITLE
When distributed,granfana diagrams only have users  

### ISSUE THREAD

**Issue by zy7y** [SvenskaSpel/locust-plugins#86]
![image](https://user-images.githubusercontent.com/67154681/162168258-02930cf3-0bd1-478e-86a4-dcb10ab37f59.png)

# master code
```python
from locust import FastHttpUser, task
import locust_plugins
# from common.load_shapes import StagesShape


class Dummy(FastHttpUser):

    @task
    def hello(self):
        pass
```
# worker code
```python
from locust import FastHttpUser
from locust import task


class Dummy(FastHttpUser):
    host = "xxxxxx"
    @task
    def hello(self):
        self.client.get("/posts")
```

# my shell
```shell
locust --timescale --headless -f master.py --pguser postgres --pgpassword password --master --expect-workers=1

locust -f worker.py --workder
```
# use docker-compose.yml
```yml
version: "3"

services:
  postgres:
    image: cyberw/locust-timescale:2
    networks:
      - timenet
    expose:
      - 5432
    ports:
      # remove the 127.0.0.1 to expose postgres to other machines (including load gen workers outside this machine)
      - 127.0.0.1:5432:5432
    environment:
      # change the password if you intend to expose postgres to other machines
      - POSTGRES_PASSWORD=password
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: cyberw/locust-grafana:2
    environment:
      # these settings are not particularly safe, dont go exposing Grafana externally without changing this.
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_LOG_LEVEL=warn # reduce log spamming. Remove this if you need to debug grafana.
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - timenet
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  timenet: null

volumes:
  postgres_data: null
  grafana_data: null
```
I'm very sorry. Could you tell me what I should do? Thank you
